### ISSUE TITLE
I need the ability to freely place slopes in different orientations

### ISSUE THREAD

**Issue by NineteenReincarnation** [pkhead/rained#10]
Thank you for your hard work. My version is 2.0.4. 
I want to ask about the slopes—Is there any way to place slopes directly without needing to base them on already placed walls? 
I really need the ability to freely switch between different orientations and place slopes directly

**Comment by pkhead** [comment]
No. This is a limitation on how Rain World handles slopes.

Technically you can do this by placing a slope and then removing the walls around it, but the slope's geometry might not load properly when you load the level in-game. The visuals would be fine, though.

But regardless, I unfortunately won't be adding this feature.
