### ISSUE TITLE
Missing Slag & Corruption No Eye effects

### ISSUE THREAD

**Issue by LudoCrypt** [pkhead/rained#2]
The effects editor is currently missing both Slag and Corruption No Eye
Edit: They're the same effect, Corruption No Eye is never used and Slag is only used in Submerged Superstructure
Edit 2: Altho rwe+ doesn't have Slag but does have Corruption No Eye so maybe add both for cross compatibility since it crashes when trying to load an unrecognized effect

**Comment by pkhead** [comment]
I didn't add those effects because the community editor seems to lack them.

**Comment by Drag64** [comment]
It would be nice to have anyways, and I could have sworn I saw that slag effect in the Downpour editor. I would check but I no longer have it. Personally I was planning to use that effect in a region I was working on, and I will resume eventually. And I'm sure other people would like to use it too.

**Comment by pkhead** [comment]
Sorry for my inaction. I will definitely add the ability to *load* Slag and Corruption No Eye, but I feel like I shouldn't add the ability to create them. Their generation shares the same code in the renderer as dead-colored Wastewater Mold from Drought Plants, and I'm not actually sure why they're omitted in the community editor but included in the Downpour one. But as Rained uses the community editor's renderer I prioritize maintaining equality with that.
