### ISSUE TITLE
Multiple opened files

### ISSUE THREAD

**Issue by tvardero** [pkhead/rained#20]
Currently I'm unable to neither open second file in parallel (without closing the first), nor opening second instance of Rained.
This makes me use other leditors to open second file in parallel.

I need to open second file as a reference for myself.

**Comment by pkhead** [comment]
Oh, I didn't realize that opening more than one instance of Rained was impossible. It looks like it's due to the fact that it can't open the log file since it's already in use by the first instance. That's actually a bug, lol.

**Comment by pkhead** [comment]
This feature is now on the nightly release. Will make a proper release sometime soon, as I still have a few features I'd like to implement before then.
