### ISSUE TITLE
(Bug) Prop editor: some props are transparent in editor

### ISSUE THREAD

**Issue by tvardero** [pkhead/rained#22]
Some props in prop editor are missing their preview image, are not visible in editor window (viewport). 

However they are successfuly placed (cant place another prop in place) and they are rendered. (See screenshots, `Giant pipe horizontal` is used as an example).

![image](https://github.com/user-attachments/assets/f9ef745b-0272-4608-acd1-e0d26f623e58)
![LR_SU1_1](https://github.com/user-attachments/assets/884ee97b-0ca0-4b7f-9dd3-e291bbf6cbe7)

Have tried reinstalling Rained, using `Data` folder from `RWE+` - results are all same.

Following props are invalid:
```txt
Pipes - Giant pipe horizontal
Special pipes - insidePipeHorizontalB
Special pipes - insidePipeVerticalB
Custom - braintree (has huge X axis offset)
```

**Comment by pkhead** [comment]
I'm pretty sure those tile inits are just broken; they appear that way in the community editor.

**Comment by tvardero** [comment]
Who should I contact to delegate this issue?
