### ISSUE TITLE
GPU memory leak when switching Edit Modes.

### ISSUE THREAD

**Issue by SimpleWolf** [pkhead/rained#25]
![image](https://github.com/user-attachments/assets/b81a6b23-1b9b-4fb8-ab2f-27a82c6580a5)

Hello, I was earlier trying to figure out what was hoarding all of my GPU memory and eventually discovered that rained's Edit Mode is a little bugged and seems to have a memory leak.

# Reproducing the Bug
1. Open Rained and view Task Manager GPU Performance
2. Switch Edit mode tabs multiple times
3. Watch your GPU memory usage explode.

![This-is-Fine-300x300](https://github.com/user-attachments/assets/22cdf32b-d356-458a-97e9-a5d7e22f46d2)

**Comment by pkhead** [comment]
Oh.

**Comment by pkhead** [comment]
fixed with 91e7aba34c0f3cd1edab206d958107a08de9fa47
