### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by Alfor564** [pkhead/rained#6]
![Снимок экрана 2024-07-05 213248](https://github.com/pkhead/rained/assets/163665790/1f2a9558-487c-4e66-acea-f339b6f763ff)

**Comment by pkhead** [comment]
In v2.0.1, I've made it so that if you type `Rained.Console.exe --gl-debug` on the command line, it will print GL debug messages. Could you try that on your computer and show me what it says? This error doesn't happen for me, so I need some help debugging this.

**Comment by pkhead** [comment]
I've changed Rained to use a different renderer in v2.0.4, which should fix the graphics driver compatibility issue.
