### ISSUE TITLE
It won't open

### ISSUE THREAD

**Issue by MrIdiot57** [pkhead/rained#7]
I just downloaded Rained for the first time, but it closes immediately after it appears in the taskbar. I installed the Visual Studio thing and restarted my computer. Twice. No clue what's happening.

**Comment by pkhead** [comment]
Sorry for the inconvenience. I'll try to investigate this issue. Try installing b1.5.3 instead, for now.

**Comment by pkhead** [comment]
I've changed Rained to use a different renderer in v2.0.4, which should fix the graphics driver compatibility issue.
