### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by NineteenReincarnation** [pkhead/rained#8]
Cannot start; when I click on the .exe file, a black window pops up and then the application disappears. I have Visual Studio installed, but I don't understand.

**Comment by NineteenReincarnation** [comment]
I am able to use version b1.5.3, and this editor is currently my favorite. I hope the author can fix the bugs as I am very eager to experience the new version! Thank you for your contribution!

**Comment by pkhead** [comment]
Can you send the contents of log/latest.log.txt after the program opens and crashes? Also, try using the latest nightly version. The newer releases have known problems with its renderer, so I have changed it, but I have yet to officially release a version with it.

**Comment by NineteenReincarnation** [comment]
latest.log.txt didn't record any content. But I can open the nightly version normally, which is exciting.

**Comment by pkhead** [comment]
That's good. I've added the new renderer in v2.0.4, which should fix this graphics driver compatibility issue.
